/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package krypt.gui;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.filechooser.FileNameExtensionFilter;
import krypt.data.FileContainer;
import krypt.service.algorithms.AESAlgorithmImplementation;

/**
 *
 * @author macze
 */
public class MainWindow extends javax.swing.JFrame {

    public static void showError(Exception ex) {
        JOptionPane.showMessageDialog(INSTANCE, "Błąd wczytywania pliku!", "Błąd wczytywania Pliku!", JOptionPane.ERROR_MESSAGE);
    }

    public static MainWindow getInstance() {
        return INSTANCE;
    }
    private static MainWindow INSTANCE;
    private FileChooserDialog fileChooserDialog;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        INSTANCE = this;
        fileChooserDialog = new FileChooserDialog(this, true);
        fileChooserDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                fileChooserDialog.setVisible(false);
            }
        });
        initComponents();
    }

    public String getSelectedRadio() {
        return algorytmy.getSelection().getActionCommand();
    }

    public void printFiles() {
        printOnTextArea(decrypted, FileContainer.getInstance().getAllLinesDecrypted());
        printOnTextArea(encrypted, FileContainer.getInstance().getAllLinesDecrypted());
    }

    private void printOnTextArea(JTextArea area, List text) {
        area.setText("");
        for (Iterator iterator = text.iterator(); iterator.hasNext();) {
            String line = (String) iterator.next();
            area.append(line + "\n");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        algorytmy = new javax.swing.ButtonGroup();
        readAndEncrypt = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        decrypted = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        encrypted = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButtonOdszyfruj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        readAndEncrypt.setText("Wczytaj plik i zaszyfruj");
        readAndEncrypt.setActionCommand("readAndEncrypt");
        readAndEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readAndEncryptActionPerformed(evt);
            }
        });

        algorytmy.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("AES");
        jRadioButton1.setActionCommand("AESAlgorithmImplementation");

        algorytmy.add(jRadioButton2);
        jRadioButton2.setText("ElGamal");
        jRadioButton2.setActionCommand("ElGamalAlgorithmImplementation");

        algorytmy.add(jRadioButton3);
        jRadioButton3.setText("DSA");
        jRadioButton3.setActionCommand("DSAAlgorithmImplementation");

        jLabel1.setText("Wybierz algorytm szyfrowania");

        decrypted.setEditable(false);
        decrypted.setColumns(20);
        decrypted.setRows(5);
        jScrollPane1.setViewportView(decrypted);

        jLabel2.setText("Tekst niezaszyfrowany");

        encrypted.setEditable(false);
        encrypted.setColumns(20);
        encrypted.setRows(5);
        jScrollPane2.setViewportView(encrypted);

        jLabel3.setText("Szyfrogram");

        jButtonOdszyfruj.setText("Otwórz plik i odszyfruj");
        jButtonOdszyfruj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdszyfrujActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1)
                    .addComponent(readAndEncrypt)
                    .addComponent(jLabel1)
                    .addComponent(jButtonOdszyfruj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(readAndEncrypt)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonOdszyfruj))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void readAndEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readAndEncryptActionPerformed

        JFileChooser chooser = new JFileChooser();
        AESAlgorithmImplementation aes = new AESAlgorithmImplementation();
       
        FileNameExtensionFilter filterOnlyCSV = new FileNameExtensionFilter("ods", "ODS", "csv", "CSV", "txt");
        chooser.setFileFilter(filterOnlyCSV);
        File file = null;
        try {
            chooser.showOpenDialog(null);
            file = chooser.getSelectedFile();

        } catch (NullPointerException e) {
            System.out.println("nie wybrano pliku");
        }
        aes.readAndAncrypt(file, decrypted, encrypted);

        


    }//GEN-LAST:event_readAndEncryptActionPerformed

    private void jButtonOdszyfrujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdszyfrujActionPerformed
        JFileChooser chooser = new JFileChooser();
        AESAlgorithmImplementation aes = new AESAlgorithmImplementation();
        
        FileNameExtensionFilter filterOnlyCSV = new FileNameExtensionFilter("ods", "ODS", "csv", "CSV", "txt", "bin");
        chooser.setFileFilter(filterOnlyCSV);
        File file = null;

        try {
            chooser.showOpenDialog(null);
            file = chooser.getSelectedFile();
            //String fileCSVname = file.getAbsolutePath();

        } catch (NullPointerException e) {
            System.out.println("nie wybrano pliku");
        }
        
        aes.decryptAndSave(file, decrypted, encrypted);


    }//GEN-LAST:event_jButtonOdszyfrujActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup algorytmy;
    private javax.swing.JTextArea decrypted;
    private javax.swing.JTextArea encrypted;
    private javax.swing.JButton jButtonOdszyfruj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton readAndEncrypt;
    // End of variables declaration//GEN-END:variables
}
